version: '3.8'

services:
  server:
    image: kagurazakanyaa/bind9:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ROOT_PASSWORD=bind
    ports:
      - 53:53/udp
      - 53:53/tcp
      - 953:953/tcp
      - 10000:10000/tcp
    volumes:
      - ./data/webmin:/etc/webmin
      - ./data/bind/etc:/etc/bind
      - ./data/bind/lib:/var/lib/bind
      - ./data/bind/cache:/var/cache/bind
